#!/bin/bash

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag docs.kubesphere.io kubesphere/docs.kubesphere.io:v1.0
docker push kubesphere/docs.kubesphere.io:v1.0